
filebeat.modules:

# List of inputs to fetch data.
filebeat.inputs:
  - paths:
      - "/var/log/logstash/logstash-default-*.log"
    type: log
    enabled: true
    document_type: logstash
    fields_under_root: true
    fields:
      service_name: logstash
      env_name: ${ENV_NAME}
      ip_address: ${IP_ADDRESS}

  - paths:
      - "/var/log/besu/*.log"
    type: log
    enabled: true
    document_type: besu
    fields_under_root: true
    fields:
      service_name: besu
      env_name: ${ENV_NAME}
      ip_address: ${IP_ADDRESS}

output.redis:
  enabled: true
  hosts: ["${REDIS_HOST}:${REDIS_PORT}"]
  key: filebeat
  #db: 0
  #datatype: list
  #loadbalance: true
  # The Redis connection timeout in seconds. The default is 5 seconds.
  #timeout: 5s
  #max_retries: 3
  #backoff.init: 1s
  #backoff.max: 60s
  #bulk_max_size: 2048
  #codec.json:
    # Pretty print json event
    #pretty: false
    # Configure escaping HTML symbols in strings.
    #escape_html: false

logging:
  level: error
  metrics.enabled: false
  to_files: false
  json: true
  files:
    path: /var/log/filebeat
    name: filebeat-all.log
    keepfiles: 0
    #rotateonstartup: true

