version: '2.2'
services:
  bootnode:
    build:
      context: pantheon/.
      args:
        PANTHEON_VERSION: ${PANTHEON_VERSION}
    image: quickstart/pantheon:${PANTHEON_VERSION}
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    entrypoint: /opt/pantheon/bootnode_start.sh --network=dev
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
  minernode:
    image: quickstart/pantheon:${PANTHEON_VERSION}
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev",
              "--miner-enabled",
              "--miner-coinbase=${MINER_COINBASE}"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode
  node:
    image: quickstart/pantheon:${PANTHEON_VERSION}
    environment:
      - PANTHEON_PUBLIC_KEY_DIRECTORY=${PANTHEON_PUBLIC_KEY_DIRECTORY}
    command: ["--network=dev"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode
  rpcnode:
    image: quickstart/pantheon:${PANTHEON_VERSION}
    command: ["--network=dev",
              "--rpc-http-enabled",
              "--rpc-http-host=0.0.0.0",
              "--rpc-http-port=8545",
              "--rpc-http-cors-origins=*",
              "--rpc-ws-enabled",
              "--rpc-ws-host=0.0.0.0",
              "--rpc-ws-port=8546",
              "--host-whitelist=*"]
    volumes:
      - public-keys:${PANTHEON_PUBLIC_KEY_DIRECTORY}
    depends_on:
      - bootnode
  explorer:
    build: block-explorer-light/.
    image: "quickstart/block-explorer-light:${PANTHEON_VERSION}"
    depends_on:
      - rpcnode
    ports:
      - "${EXPLORER_PORT_MAPPING:-}80"
volumes:
  public-keys:
