---
  version: '3.4'
  services:

    orion1:
      image: "pegasyseng/orion:develop"
      command: ["/config/orion/orion.conf"]
      volumes:
        - ./config/orion/networkFiles/orion1:/config/orion/

    orion2:
      image: "pegasyseng/orion:develop"
      command: ["/config/orion/orion.conf"]
      volumes:
        - ./config/orion/networkFiles/orion2:/config/orion/

    orion3:
      image: "pegasyseng/orion:develop"
      command: ["/config/orion/orion.conf"]
      volumes:
        - ./config/orion/networkFiles/orion3:/config/orion/

    bootnode:
      build:
        context: besu/.
        args:
          BESU_VERSION: ${BESU_VERSION}
      image: quickstart/besu:${BESU_VERSION}
      environment:
        - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      entrypoint: /opt/besu/bootnode_start.sh
      command: [
        "--config-file=/config/config.toml",
        "--genesis-file=/config/genesis.json",
        "--node-private-key-file=/opt/besu/keys/key",
        "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}" ]
      volumes:
        - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
        - ./config/besu/config.toml:/config/config.toml
        - ./config/besu/${QUICKSTART_POA_NAME-ibft2}Genesis.json:/config/genesis.json
        - ./config/besu/networkFiles/bootnode/keys:/opt/besu/keys

    rpcnode: #  We keep one node named rpcnode to have a specific node to connect the explorer
      image: quickstart/besu:${BESU_VERSION}
      environment:
        - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      command: [
        "--config-file=/config/config.toml",
        "--genesis-file=/config/genesis.json",
        "--node-private-key-file=/opt/besu/keys/key",
        "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}" ]
      volumes:
        - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
        - ./config/besu/config.toml:/config/config.toml
        - ./config/besu/${QUICKSTART_POA_NAME-ibft2}Genesis.json:/config/genesis.json
        - ./config/besu/networkFiles/rpcnode/keys:/opt/besu/keys
      depends_on:
        - bootnode
      ports:
        - 8545:8545/tcp

    node1:
      image: quickstart/besu:${BESU_VERSION}
      environment:
        - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      command: [
        "--config-file=/config/config.toml",
        "--genesis-file=/config/genesis.json",
        "--node-private-key-file=/opt/besu/keys/key",
        "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--min-gas-price=0",
        "--privacy-enabled=true",
        "--privacy-url=http://orion1:8888",
        "--privacy-public-key-file=/config/orion/orion.pub"]
      volumes:
        - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
        - ./config/besu/config.toml:/config/config.toml
        - ./config/besu/${QUICKSTART_POA_NAME-ibft2}Genesis.json:/config/genesis.json
        - ./config/besu/networkFiles/node3/keys:/opt/besu/keys
        - ./config/orion/networkFiles/orion1/nodeKey.pub:/config/orion/orion.pub
      depends_on:
        - bootnode
        - orion1
      ports:
        - 20000:8545/tcp
        - 20001:8546/tcp

    node2:
      image: quickstart/besu:${BESU_VERSION}
      environment:
        - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      command: [
        "--config-file=/config/config.toml",
        "--genesis-file=/config/genesis.json",
        "--node-private-key-file=/opt/besu/keys/key",
        "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--min-gas-price=0",
        "--privacy-enabled=true",
        "--privacy-url=http://orion2:8888",
        "--privacy-public-key-file=/config/orion/orion.pub"]
      volumes:
        - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
        - ./config/besu/config.toml:/config/config.toml
        - ./config/besu/${QUICKSTART_POA_NAME-ibft2}Genesis.json:/config/genesis.json
        - ./config/besu/networkFiles/node4/keys:/opt/besu/keys
        - ./config/orion/networkFiles/orion2/nodeKey.pub:/config/orion/orion.pub
      depends_on:
        - bootnode
        - orion2
      ports:
        - 20002:8545/tcp
        - 20003:8546/tcp

    node3:
      image: quickstart/besu:${BESU_VERSION}
      environment:
        - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      command: [
        "--config-file=/config/config.toml",
        "--genesis-file=/config/genesis.json",
        "--node-private-key-file=/opt/besu/keys/key",
        "--rpc-http-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN,PRIV,${QUICKSTART_POA_API-ibft}",
        "--min-gas-price=0",
        "--privacy-enabled=true",
        "--privacy-url=http://orion3:8888",
        "--privacy-public-key-file=/config/orion/orion.pub"]
      volumes:
        - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
        - ./config/besu/config.toml:/config/config.toml
        - ./config/besu/${QUICKSTART_POA_NAME-ibft2}Genesis.json:/config/genesis.json
        - ./config/besu/networkFiles/node5/keys:/opt/besu/keys
        - ./config/orion/networkFiles/orion3/nodeKey.pub:/config/orion/orion.pub
      depends_on:
        - bootnode
        - orion3
      ports:
        - 20004:8545/tcp
        - 20005:8546/tcp

    explorer:
      build: block-explorer-light/.
      image: quickstart/block-explorer-light:${BESU_VERSION}-${QUICKSTART_POA_NAME-ibft2}
      depends_on:
        - rpcnode
      ports:
        - 25000:80/tcp

    prometheus:
      image: "prom/prometheus"
      volumes:
        - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus:/prometheus
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090/tcp

    grafana:
      image: "grafana/grafana"
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
      volumes:
        - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
        - grafana:/var/lib/grafana
      ports:
        - 3000:3000/tcp

  volumes:
    public-keys:

    prometheus:

    grafana:
