---
version: '3.4'
services:

  bootnode:
    build:
      context: besu/.
      args:
        BESU_VERSION: ${BESU_VERSION}
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    entrypoint: /opt/besu/bootnode_start.sh --network=dev --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9545 --host-whitelist=*
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp

  minernode:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: [
      "--network=dev",
      "--miner-enabled",
      "--metrics-enabled",
      "--metrics-host=0.0.0.0",
      "--metrics-port=9545",
      "--miner-coinbase=${MINER_COINBASE}",
      "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
    depends_on:
      - bootnode

  node:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: [
      "--network=dev",
      "--metrics-enabled",
      "--metrics-host=0.0.0.0",
      "--metrics-port=9545",
      "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
    depends_on:
      - bootnode

  rpcnode:
    image: sample-network/besu:${BESU_VERSION}
    environment:
      - BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
    command: [
      "--network=dev",
      "--rpc-http-enabled",
      "--rpc-http-host=0.0.0.0",
      "--rpc-http-port=8545",
      "--rpc-http-cors-origins=*",
      "--rpc-ws-enabled",
      "--rpc-ws-host=0.0.0.0",
      "--rpc-ws-port=8546",
      "--metrics-enabled",
      "--metrics-host=0.0.0.0",
      "--metrics-port=9545",
      "--graphql-http-enabled",
      "--graphql-http-host=0.0.0.0",
      "--graphql-http-port=8547",
      "--graphql-http-cors-origins=*",
      "--host-whitelist=*"]
    volumes:
      - public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/besu/log-config.xml:/config/log-config.xml
      - ./logs/besu:/var/log/
    depends_on:
      - bootnode
    ports:
      - 8545:8545/tcp

  explorer:
    build: block-explorer-light/.
    image: "sample-network/block-explorer-light:${BESU_VERSION}"
    depends_on:
      - rpcnode
    ports:
      - 25000:80/tcp

  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

volumes:
  public-keys:

  prometheus:

  grafana:
