#!/bin/sh -e

# Copyright 2018 ConsenSys AG.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

. ./.env

me=`basename "$0"`

displayUsage()
{
  echo "Usage: ${me} [OPTIONS]"
  echo "    -k or --keep-images : do not remove the Docker images generated by run script"
  exit 0
}

keepImages=false

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      displayUsage
      ;;
    -k|--keep-images)
      keepImages=true
      shift 1
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag." >&2
      displayUsage
      ;;
  esac
done

version=$QUICKSTART_VERSION
composeFile=""
if [ -f ${LOCK_FILE} ]; then
    composeFile=`sed '1q;d' ${LOCK_FILE}`
    version=`sed '2q;d' ${LOCK_FILE}`
fi

docker-compose ${composeFile} down -v
docker-compose ${composeFile} rm -sfv

if [ "${keepImages}" = "false" ];then
  docker image rm quickstart/pantheon:${version}
  docker image rm quickstart/block-explorer-light:${version}
fi

rm ${LOCK_FILE}
