{
 "title": "Pantheon Overview",
 "description": "Provides an overview of Pantheon nodes",
 "tags": [
  "pantheon",
  "ethereum"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": "pantheon_blockchain_height" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (pantheon_blockchain_height{instance=~\"$system\"})",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (pantheon_synchronizer_best_known_block{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (pantheon_synchronizer_best_known_block{instance=~\"$system\"} - pantheon_blockchain_height{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (pantheon_blockchain_difficulty_total{instance=~\"$system\"})",
     "legendFormat": "Total Difficulty"
    },
    {
     "expr": "sum by (instance) (1/rate(pantheon_blockchain_height{instance=~\"$system\"}[5m]))"
    },
    {
     "expr": "sum by (instance) (time() - pantheon_blockchain_chain_head_timestamp{instance=~\"$system\"})"
    },
    {
     "expr": "sum by (instance) (pantheon_peers_peer_count_current{instance=~\"$system\"})",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (instance) (pantheon_peers_peer_count_current{instance=~\"$system\"} / pantheon_network_peers_limit{instance=~\"$system\"})"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(pantheon_blockchain_height{instance=~\"$system\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {}
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "pantheon_synchronizer_best_known_block{instance=~\"$system\"} - pantheon_blockchain_height{instance=~\"$system\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"$system\", area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{instance=~\"$system\", area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}